
import type { Gender, EducationLevel, MaritalStatus, CustodyStatus } from '@/types/suspect';

export const GENDERS: { value: Gender; label: string }[] = [
  { value: "Male", label: "Male" },
  { value: "Female", label: "Female" },
  { value: "Other", label: "Other" },
];

export const EDUCATION_LEVELS: { value: EducationLevel; label: string }[] = [
  { value: "None", label: "No Formal Education" },
  { value: "Primary", label: "Primary School" },
  { value: "JHS/Middle School", label: "JHS / Middle School" },
  { value: "SHS/Secondary", label: "SHS / Secondary School" },
  { value: "Vocational/Technical", label: "Vocational / Technical" },
  { value: "Tertiary", label: "Tertiary Education" },
  { value: "Postgraduate", label: "Postgraduate Studies" },
];

export const MARITAL_STATUSES: { value: MaritalStatus; label: string }[] = [
  { value: "Single", label: "Single" },
  { value: "Married", label: "Married" },
  { value: "Divorced", label: "Divorced" },
  { value: "Widowed", label: "Widowed" },
  { value: "Separated", label: "Separated" },
];

export const NATIONALITIES: { value: string; label: string }[] = [
  { value: "Afghan", label: "Afghan" },
  { value: "Albanian", label: "Albanian" },
  { value: "Algerian", label: "Algerian" },
  { value: "American", label: "American" },
  { value: "Andorran", label: "Andorran" },
  { value: "Angolan", label: "Angolan" },
  { value: "Antiguans", label: "Antiguans" },
  { value: "Argentinean", label: "Argentinean" },
  { value: "Armenian", label: "Armenian" },
  { value: "Australian", label: "Australian" },
  { value: "Austrian", label: "Austrian" },
  { value: "Azerbaijani", label: "Azerbaijani" },
  { value: "Bahamian", label: "Bahamian" },
  { value: "Bahraini", label: "Bahraini" },
  { value: "Bangladeshi", label: "Bangladeshi" },
  { value: "Barbadian", label: "Barbadian" },
  { value: "Barbudans", label: "Barbudans" },
  { value: "Batswana", label: "Batswana" },
  { value: "Belarusian", label: "Belarusian" },
  { value: "Belgian", label: "Belgian" },
  { value: "Belizean", label: "Belizean" },
  { value: "Beninese", label: "Beninese" },
  { value: "Bhutanese", label: "Bhutanese" },
  { value: "Bolivian", label: "Bolivian" },
  { value: "Bosnian", label: "Bosnian" },
  { value: "Brazilian", label: "Brazilian" },
  { value: "British", label: "British" },
  { value: "Bruneian", label: "Bruneian" },
  { value: "Bulgarian", label: "Bulgarian" },
  { value: "Burkinabe", label: "Burkinabe" },
  { value: "Burmese", label: "Burmese" },
  { value: "Burundian", label: "Burundian" },
  { value: "Cambodian", label: "Cambodian" },
  { value: "Cameroonian", label: "Cameroonian" },
  { value: "Canadian", label: "Canadian" },
  { value: "Cape Verdean", label: "Cape Verdean" },
  { value: "Central African", label: "Central African" },
  { value: "Chadian", label: "Chadian" },
  { value: "Chilean", label: "Chilean" },
  { value: "Chinese", label: "Chinese" },
  { value: "Colombian", label: "Colombian" },
  { value: "Comoran", label: "Comoran" },
  { value: "Congolese (Congo-Brazzaville)", label: "Congolese (Congo-Brazzaville)" },
  { value: "Congolese (DRC)", label: "Congolese (DRC)" },
  { value: "Costa Rican", label: "Costa Rican" },
  { value: "Croatian", label: "Croatian" },
  { value: "Cuban", label: "Cuban" },
  { value: "Cypriot", label: "Cypriot" },
  { value: "Czech", label: "Czech" },
  { value: "Danish", label: "Danish" },
  { value: "Djibouti", label: "Djibouti" },
  { value: "Dominican (Dominica)", label: "Dominican (Dominica)" },
  { value: "Dominican (Dominican Republic)", label: "Dominican (Dominican Republic)" },
  { value: "Dutch", label: "Dutch" },
  { value: "East Timorese", label: "East Timorese" },
  { value: "Ecuadorean", label: "Ecuadorean" },
  { value: "Egyptian", label: "Egyptian" },
  { value: "Emirian", label: "Emirian" },
  { value: "Equatorial Guinean", label: "Equatorial Guinean" },
  { value: "Eritrean", label: "Eritrean" },
  { value: "Estonian", label: "Estonian" },
  { value: "Ethiopian", label: "Ethiopian" },
  { value: "Fijian", label: "Fijian" },
  { value: "Filipino", label: "Filipino" },
  { value: "Finnish", label: "Finnish" },
  { value: "French", label: "French" },
  { value: "Gabonese", label: "Gabonese" },
  { value: "Gambian", label: "Gambian" },
  { value: "Georgian", label: "Georgian" },
  { value: "German", label: "German" },
  { value: "Ghanaian", label: "Ghanaian" },
  { value: "Greek", label: "Greek" },
  { value: "Grenadian", label: "Grenadian" },
  { value: "Guatemalan", label: "Guatemalan" },
  { value: "Guinea-Bissauan", label: "Guinea-Bissauan" },
  { value: "Guinean", label: "Guinean" },
  { value: "Guyanese", label: "Guyanese" },
  { value: "Haitian", label: "Haitian" },
  { value: "Herzegovinian", label: "Herzegovinian" },
  { value: "Honduran", label: "Honduran" },
  { value: "Hungarian", label: "Hungarian" },
  { value: "I-Kiribati", label: "I-Kiribati" },
  { value: "Icelandic", label: "Icelandic" },
  { value: "Indian", label: "Indian" },
  { value: "Indonesian", label: "Indonesian" },
  { value: "Iranian", label: "Iranian" },
  { value: "Iraqi", label: "Iraqi" },
  { value: "Irish", label: "Irish" },
  { value: "Israeli", label: "Israeli" },
  { value: "Italian", label: "Italian" },
  { value: "Ivorian", label: "Ivorian" },
  { value: "Jamaican", label: "Jamaican" },
  { value: "Japanese", label: "Japanese" },
  { value: "Jordanian", label: "Jordanian" },
  { value: "Kazakhstani", label: "Kazakhstani" },
  { value: "Kenyan", label: "Kenyan" },
  { value: "Kittian and Nevisian", label: "Kittian and Nevisian" },
  { value: "Kuwaiti", label: "Kuwaiti" },
  { value: "Kyrgyz", label: "Kyrgyz" },
  { value: "Laotian", label: "Laotian" },
  { value: "Latvian", label: "Latvian" },
  { value: "Lebanese", label: "Lebanese" },
  { value: "Liberian", label: "Liberian" },
  { value: "Libyan", label: "Libyan" },
  { value: "Liechtensteiner", label: "Liechtensteiner" },
  { value: "Lithuanian", label: "Lithuanian" },
  { value: "Luxembourger", label: "Luxembourger" },
  { value: "Macedonian", label: "Macedonian" },
  { value: "Malagasy", label: "Malagasy" },
  { value: "Malawian", label: "Malawian" },
  { value: "Malaysian", label: "Malaysian" },
  { value: "Maldivan", label: "Maldivan" },
  { value: "Malian", label: "Malian" },
  { value: "Maltese", label: "Maltese" },
  { value: "Marshallese", label: "Marshallese" },
  { value: "Mauritanian", label: "Mauritanian" },
  { value: "Mauritian", label: "Mauritian" },
  { value: "Mexican", label: "Mexican" },
  { value: "Micronesian", label: "Micronesian" },
  { value: "Moldovan", label: "Moldovan" },
  { value: "Monacan", label: "Monacan" },
  { value: "Mongolian", label: "Mongolian" },
  { value: "Montenegrin", label: "Montenegrin" },
  { value: "Moroccan", label: "Moroccan" },
  { value: "Mosotho", label: "Mosotho" },
  { value: "Motswana", label: "Motswana" },
  { value: "Mozambican", label: "Mozambican" },
  { value: "Namibian", label: "Namibian" },
  { value: "Nauruan", label: "Nauruan" },
  { value: "Nepalese", label: "Nepalese" },
  { value: "New Zealander", label: "New Zealander" },
  { value: "Nicaraguan", label: "Nicaraguan" },
  { value: "Nigerian", label: "Nigerian" },
  { value: "Nigerien", label: "Nigerien" },
  { value: "North Korean", label: "North Korean" },
  { value: "Northern Irish", label: "Northern Irish" },
  { value: "Norwegian", label: "Norwegian" },
  { value: "Omani", label: "Omani" },
  { value: "Pakistani", label: "Pakistani" },
  { value: "Palauan", label: "Palauan" },
  { value: "Palestinian", label: "Palestinian" },
  { value: "Panamanian", label: "Panamanian" },
  { value: "Papua New Guinean", label: "Papua New Guinean" },
  { value: "Paraguayan", label: "Paraguayan" },
  { value: "Peruvian", label: "Peruvian" },
  { value: "Polish", label: "Polish" },
  { value: "Portuguese", label: "Portuguese" },
  { value: "Qatari", label: "Qatari" },
  { value: "Romanian", label: "Romanian" },
  { value: "Russian", label: "Russian" },
  { value: "Rwandan", label: "Rwandan" },
  { value: "Saint Lucian", label: "Saint Lucian" },
  { value: "Salvadoran", label: "Salvadoran" },
  { value: "Samoan", label: "Samoan" },
  { value: "San Marinese", label: "San Marinese" },
  { value: "Sao Tomean", label: "Sao Tomean" },
  { value: "Saudi", label: "Saudi" },
  { value: "Scottish", label: "Scottish" },
  { value: "Senegalese", label: "Senegalese" },
  { value: "Serbian", label: "Serbian" },
  { value: "Seychellois", label: "Seychellois" },
  { value: "Sierra Leonean", label: "Sierra Leonean" },
  { value: "Singaporean", label: "Singaporean" },
  { value: "Slovakian", label: "Slovakian" },
  { value: "Slovenian", label: "Slovenian" },
  { value: "Solomon Islander", label: "Solomon Islander" },
  { value: "Somali", label: "Somali" },
  { value: "South African", label: "South African" },
  { value: "South Korean", label: "South Korean" },
  { value: "Spanish", label: "Spanish" },
  { value: "Sri Lankan", label: "Sri Lankan" },
  { value: "Sudanese", label: "Sudanese" },
  { value: "Surinamer", label: "Surinamer" },
  { value: "Swazi", label: "Swazi" },
  { value: "Swedish", label: "Swedish" },
  { value: "Swiss", label: "Swiss" },
  { value: "Syrian", label: "Syrian" },
  { value: "Taiwanese", label: "Taiwanese" },
  { value: "Tajik", label: "Tajik" },
  { value: "Tanzanian", label: "Tanzanian" },
  { value: "Thai", label: "Thai" },
  { value: "Togolese", label: "Togolese" },
  { value: "Tongan", label: "Tongan" },
  { value: "Trinidadian or Tobagonian", label: "Trinidadian or Tobagonian" },
  { value: "Tunisian", label: "Tunisian" },
  { value: "Turkish", label: "Turkish" },
  { value: "Tuvaluan", label: "Tuvaluan" },
  { value: "Ugandan", label: "Ugandan" },
  { value: "Ukrainian", label: "Ukrainian" },
  { value: "Uruguayan", label: "Uruguayan" },
  { value: "Uzbekistani", label: "Uzbekistani" },
  { value: "Venezuelan", label: "Venezuelan" },
  { value: "Vietnamese", label: "Vietnamese" },
  { value: "Welsh", label: "Welsh" },
  { value: "Yemenite", label: "Yemenite" },
  { value: "Zambian", label: "Zambian" },
  { value: "Zimbabwean", label: "Zimbabwean" },
  { value: "Other", label: "Other" },
].sort((a, b) => a.label.localeCompare(b.label));


export const LANGUAGES_SPOKEN_SUGGESTIONS: string[] = [
  "English", "Twi", "Ga", "Ewe", "Fante", "Hausa", "Dagbani", "French"
];

export const YES_NO_OPTIONS: { value: string; label: string }[] = [
  { value: "true", label: "Yes" },
  { value: "false", label: "No" },
];

export const SKIN_TONES: { value: string; label: string }[] = [
  { value: "Fair", label: "Fair" },
  { value: "Light Brown", label: "Light Brown" },
  { value: "Medium Brown", label: "Medium Brown" },
  { value: "Dark Brown", label: "Dark Brown" },
  { value: "Black", label: "Black" },
  { value: "Other", label: "Other" },
];

export const HAIR_STYLES: { value: string; label: string }[] = [
  { value: "Short Cut", label: "Short Cut" },
  { value: "Bald", label: "Bald" },
  { value: "Afro", label: "Afro" },
  { value: "Braids", label: "Braids" },
  { value: "Dreadlocks", label: "Dreadlocks" },
  { value: "Straight", label: "Straight" },
  { value: "Curly", label: "Curly" },
  { value: "Wavy", label: "Wavy" },
  { value: "Other", label: "Other" },
];

export const HAIR_COLORS: { value: string; label: string }[] = [
  { value: "Black", label: "Black" },
  { value: "Brown", label: "Brown" },
  { value: "Dark Brown", label: "Dark Brown" },
  { value: "Blonde", label: "Blonde" },
  { value: "Red", label: "Red" },
  { value: "Grey", label: "Grey" },
  { value: "White", label: "White" },
  { value: "Other", label: "Other" },
];

export const EYE_COLORS: { value: string; label: string }[] = [
  { value: "Brown", label: "Brown" },
  { value: "Dark Brown", label: "Dark Brown" },
  { value: "Black", label: "Black" },
  { value: "Hazel", label: "Hazel" },
  { value: "Blue", label: "Blue" },
  { value: "Green", label: "Green" },
  { value: "Grey", label: "Grey" },
  { value: "Other", label: "Other" },
];

export const PHYSICAL_MARK_OPTIONS: { value: string; label: string }[] = [
  { value: "None Visible", label: "None Visible" },
  { value: "Scar - Face", label: "Scar - Face" },
  { value: "Scar - Arm (Left)", label: "Scar - Arm (Left)" },
  { value: "Scar - Arm (Right)", label: "Scar - Arm (Right)" },
  { value: "Scar - Leg (Left)", label: "Scar - Leg (Left)" },
  { value: "Scar - Leg (Right)", label: "Scar - Leg (Right)" },
  { value: "Tattoo - Arm (Left)", label: "Tattoo - Arm (Left)" },
  { value: "Tattoo - Arm (Right)", label: "Tattoo - Arm (Right)" },
  { value: "Tattoo - Chest", label: "Tattoo - Chest" },
  { value: "Tattoo - Back", label: "Tattoo - Back" },
  { value: "Birthmark - General", label: "Birthmark (General)" },
  { value: "Tribal Marks - Face", label: "Tribal Marks - Face" },
  { value: "Missing Limb - Arm (Left)", label: "Missing Limb - Arm (Left)" },
  { value: "Missing Limb - Arm (Right)", label: "Missing Limb - Arm (Right)" },
  { value: "Missing Limb - Leg (Left)", label: "Missing Limb - Leg (Left)" },
  { value: "Missing Limb - Leg (Right)", label: "Missing Limb - Leg (Right)" },
  { value: "Other - Specify in Notes", label: "Other - Specify in Notes" },
];

export const CUSTODY_STATUS_OPTIONS: { value: CustodyStatus; label: string }[] = [
  { value: "Unknown", label: "Unknown" },
  { value: "Police Custody (Active Investigation)", label: "Police Custody (Active Investigation)" },
  { value: "Remanded (Police Custody)", label: "Remanded (Police Custody)" },
  { value: "Remanded (Prison Custody)", label: "Remanded (Prison Custody)" },
  { value: "Bail (Court)", label: "Bail (Court)" },
  { value: "Bail (Police Enquiry)", label: "Bail (Police Enquiry)" },
  { value: "Released", label: "Released" },
  { value: "Wanted", label: "Wanted" },
  { value: "Deceased", label: "Deceased" },
  { value: "Other", label: "Other" },
];

// Illustrative list of offences. THIS IS NOT EXHAUSTIVE OR LEGALLY VERIFIED.
// For production, this list MUST be curated by a legal professional.
export const GHANA_LEGAL_OFFENCES: { value: string; label: string; category: string }[] = [
  // Criminal Offences Act, 1960 (Act 29)
  { value: "Assault (Act 29)", label: "Assault", category: "Criminal Offences Act" },
  { value: "Stealing (Act 29)", label: "Stealing", category: "Criminal Offences Act" },
  { value: "Robbery (Act 29)", label: "Robbery", category: "Criminal Offences Act" },
  { value: "Burglary (Act 29)", label: "Burglary", category: "Criminal Offences Act" },
  { value: "Causing Harm (Act 29)", label: "Causing Harm", category: "Criminal Offences Act" },
  { value: "Murder (Act 29)", label: "Murder", category: "Criminal Offences Act" },
  { value: "Manslaughter (Act 29)", label: "Manslaughter", category: "Criminal Offences Act" },
  { value: "Fraud by False Pretences (Act 29)", label: "Fraud by False Pretences", category: "Criminal Offences Act" },
  { value: "Defilement (Act 29)", label: "Defilement", category: "Criminal Offences Act" },
  { value: "Rape (Act 29)", label: "Rape", category: "Criminal Offences Act" },
  { value: "Threat of Harm (Act 29)", label: "Threat of Harm", category: "Criminal Offences Act" },
  { value: "Possession of Firearm without Lawful Excuse (Act 29)", label: "Possession of Firearm without Lawful Excuse", category: "Criminal Offences Act" },

  // Cybersecurity Act, 2020 (Act 1038)
  { value: "Unauthorized Access to Computer System (Act 1038)", label: "Unauthorized Access to Computer System", category: "Cybersecurity Act" },
  { value: "Cyber Fraud (Act 1038)", label: "Cyber Fraud", category: "Cybersecurity Act" },
  { value: "Online Child Pornography (Act 1038)", label: "Online Child Pornography", category: "Cybersecurity Act" },
  { value: "Cyberstalking (Act 1038)", label: "Cyberstalking", category: "Cybersecurity Act" },
  { value: "Identity Theft (Act 1038)", label: "Identity Theft", category: "Cybersecurity Act" },

  // Human Trafficking Act, 2005 (Act 694)
  { value: "Trafficking in Persons (Act 694)", label: "Trafficking in Persons", category: "Human Trafficking Act" },
  { value: "Exploitation of Trafficked Persons (Act 694)", label: "Exploitation of Trafficked Persons", category: "Human Trafficking Act" },

  // Land Act, 2020 (Act 1036) - (Specific offences might be more nuanced)
  { value: "Unlawful Dealing in Land (Act 1036)", label: "Unlawful Dealing in Land", category: "Land Act" },
  { value: "Land Grabbing (Act 1036)", label: "Land Grabbing", category: "Land Act" }, // General term

  // Anti-Money Laundering Act, 2020 (Act 1044)
  { value: "Money Laundering (Act 1044)", label: "Money Laundering", category: "Anti-Money Laundering Act" },
  { value: "Failure to Report Suspicious Transaction (Act 1044)", label: "Failure to Report Suspicious Transaction", category: "Anti-Money Laundering Act" },

  // Narcotic Drugs (Control, Enforcement and Sanctions) Act, 1990 (PNDCL 236)
  { value: "Possession of Narcotic Drugs (PNDCL 236)", label: "Possession of Narcotic Drugs", category: "Narcotic Drug Law" },
  { value: "Trafficking of Narcotic Drugs (PNDCL 236)", label: "Trafficking of Narcotic Drugs", category: "Narcotic Drug Law" },
  { value: "Cultivation of Prohibited Plants (PNDCL 236)", label: "Cultivation of Prohibited Plants (e.g., Cannabis)", category: "Narcotic Drug Law" },
  
  { value: "Other - Specify in Notes", label: "Other (Specify in Notes/Narrative)", category: "Other" },
].sort((a, b) => a.category.localeCompare(b.category) || a.label.localeCompare(b.label));
    
